repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.9
  hooks:
    # Run the linter.
    #- id: ruff
    # test of ruff-check
    - id: ruff-check
      args: [--fix]
    # Run the formatter.
    - id: ruff-format
    # Keep uv.lock up-to-date
    #- id: uv-lock
    # Keep a requirements.txt file in sync with uv.lock
    #- id: uv-export